apiVersion: apps/v1
kind: Deployment
metadata:
  name: activemq-artemis-deployment
  labels:
    app: activemq-artemis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: activemq-artemis-app
  template:
    metadata:
      labels:
        app: activemq-artemis-app
    spec:
      containers:
        - name: activemq-artemis
          image: apache/activemq-artemis:latest-alpine
          ports:
            - containerPort: 61616  # OpenWire Port
            - containerPort: 8161   # Web Console
            - containerPort: 5445   # Core Protocol
            - containerPort: 1883   # MQTT Protocol
