apiVersion: v1
kind: Service
metadata:
  name: activemq-artemis
spec:
  selector:
    app: activemq-artemis-app
  ports:
    - name: "artemis-messaging-port"
      protocol: TCP
      port: 5001
      targetPort: 61616
    - name: "artemis-http-port"
      port: 5002
      targetPort: 8161
      protocol: TCP
  type: LoadBalancer
