apiVersion: v1
kind: Service
metadata:
  name: activemq-artemis
spec:
  selector:
    app: activemq-artemis
  ports:
    - name: "artemis-messaging-port"
      protocol: TCP
      port: 61616
      targetPort: 61616
    - name: "artemis-http-port"
      port: 8161
      targetPort: 8161
      protocol: TCP
